#!/bin/sh
# Run as root on the Raspberry Pi: sudo ./install.sh
set -eu

prompt_value() {
    prompt_text=$1
    default_value=$2
    printf '%s [%s]: ' "$prompt_text" "$default_value" >&2
    read -r entered_value
    if [ -n "$entered_value" ]; then
        printf '%s' "$entered_value"
    else
        printf '%s' "$default_value"
    fi
}

prompt_secret() {
    prompt_text=$1
    printf '%s: ' "$prompt_text" >&2
    stty -echo
    if ! read -r entered_value; then
        stty echo
        printf '\n' >&2
        return 1
    fi
    stty echo
    printf '\n' >&2
    printf '%s' "$entered_value"
}

install -d -m 0750 /etc/agv-monitor /var/lib/agv-monitor /usr/local/lib/agv-monitor
install -m 0755 telemetry_agent.py /usr/local/lib/agv-monitor/telemetry_agent.py
install -m 0644 agv-monitor.service /etc/systemd/system/agv-monitor.service
if [ ! -f /etc/agv-monitor/telemetry.conf ]; then
    echo 'Configure this device (press Enter to accept a displayed default).'
    server_url=$(prompt_value 'Server telemetry URL' 'https://monitor.example.com/api/v1/telemetry')
    device_token=$(prompt_secret 'Device token')
    if [ -z "$device_token" ]; then
        echo 'A device token is required; configuration was not created.' >&2
        exit 1
    fi
    sample_interval=$(prompt_value 'Sample interval in seconds' '5')
    upload_interval=$(prompt_value 'Upload interval in seconds' '300')
    disk_path=$(prompt_value 'Filesystem path to monitor' '/')
    max_spool_samples=$(prompt_value 'Maximum locally queued samples' '120960')
    http_timeout=$(prompt_value 'HTTP timeout in seconds' '20')
    umask 077
    {
        printf '%s\n' '# Generated by install.sh. Device-specific settings are kept together here.'
        printf 'SERVER_URL=%s\n' "$server_url"
        printf 'DEVICE_TOKEN=%s\n' "$device_token"
        printf 'SAMPLE_INTERVAL_SECONDS=%s\n' "$sample_interval"
        printf 'UPLOAD_INTERVAL_SECONDS=%s\n' "$upload_interval"
        printf 'DISK_PATH=%s\n' "$disk_path"
        printf '%s\n' 'SPOOL_PATH=/var/lib/agv-monitor/telemetry-spool.jsonl'
        printf 'MAX_SPOOL_SAMPLES=%s\n' "$max_spool_samples"
        printf 'HTTP_TIMEOUT_SECONDS=%s\n' "$http_timeout"
    } > /etc/agv-monitor/telemetry.conf
    chmod 0600 /etc/agv-monitor/telemetry.conf
    systemctl daemon-reload
    systemctl enable --now agv-monitor.service
else
    systemctl daemon-reload
    systemctl enable --now agv-monitor.service
fi
